import Link from 'next/link'


const STATS = [
  { value: '7.6M+', label: 'NHS patients on waiting lists modelled', color: 'text-nhs-blue' },
  { value: '7', label: 'English NHS regions tracked in real time', color: 'text-slate-800' },
  { value: '89%', label: 'Spearman correlation — inequality score vs deprivation', color: 'text-green-700' },
  { value: '6-month', label: 'Forward forecasts from OLS regression models', color: 'text-amber-600' },
]

const FEATURES = [
  {
    title: 'Composite inequality scoring',
    description:
      'A novel weighted formula (S = 0.40W + 0.35G + 0.25D) combines waiting-time burden, regional gap, and deprivation into a single actionable metric — validated against NHS England survey data (ρ = 0.89, p < 0.001).',
    href: '/methodology',
    linkLabel: 'Read methodology',
  },
  {
    title: 'Live AI gap analysis',
    description:
      'Streaming Claude-powered explanations contextualise the inequality gap between any two NHS regions, surfacing policy levers and evidence-based interventions in seconds.',
    href: '/compare',
    linkLabel: 'Try region comparator',
  },
  {
    title: 'Automated forecasting pipeline',
    description:
      'An end-to-end ETL pipeline ingests NHS RTT open data, computes OLS regression forecasts with 95% prediction intervals, and surfaces 6-month projections per region.',
    href: '/trends',
    linkLabel: 'Explore trends',
  },
  {
    title: 'Specialty-level pressure mapping',
    description:
      'Specialty breakdown identifies which clinical areas bear the greatest backlog burden, ranked by % waiting over the 18-week constitutional standard with year-on-year change.',
    href: '/specialties',
    linkLabel: 'View specialties',
  },
  {
    title: 'Executive AI briefing',
    description:
      'A structured five-section briefing — situation, drivers, inequality, forecast, interventions — generated by Claude from live data and downloadable as a plain-text report.',
    href: '/briefing',
    linkLabel: 'Read briefing',
  },
  {
    title: 'NHS news intelligence feed',
    description:
      'RSS feeds from NHS England, BBC Health and The Guardian are triaged by Claude Haiku for relevance, tag, and clinical significance — giving analysts a filtered signal from the noise.',
    href: '/news',
    linkLabel: 'Open news feed',
  },
]

const TIMELINE = [
  { date: 'Jan 2025', event: 'Project conceived — identified gap in accessible NHS waiting-list analytics for policy researchers.' },
  { date: 'Feb 2025', event: 'NHS RTT open-data pipeline built; regional inequality score formula designed and validated.' },
  { date: 'Mar 2025', event: 'Claude AI integration added — streaming explanations, multi-turn chat, proactive insights.' },
  { date: 'Apr 2025', event: 'Region comparator, methodology documentation, and executive briefing generator shipped.' },
]

export default function AboutPage() {
  return (
    <>
      {/* Hero */}
      <div className="mb-10">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 bg-nhs-navy rounded-xl flex items-center justify-center text-white font-bold text-lg">N</div>
          <div>
            <h1 className="text-2xl font-bold text-slate-800">NHS Wait Intelligence</h1>
            <p className="text-sm text-slate-500">Open analytics platform for NHS waiting-list equity research</p>
          </div>
        </div>
        <p className="text-slate-600 leading-relaxed max-w-3xl mt-4">
          NHS Wait Intelligence turns publicly available NHS Reference Times (RTT) data into an interactive
          intelligence platform — surfacing regional inequalities, forecasting backlog trajectories, and
          delivering AI-powered explanations that help policymakers, researchers, and commissioners act faster.
        </p>
        <div className="flex flex-wrap gap-3 mt-5">
          <Link href="/methodology" className="px-5 py-2.5 bg-nhs-navy text-white text-sm font-semibold rounded-full hover:bg-nhs-blue transition-colors">
            Read methodology
          </Link>
          <Link href="/compare" className="px-5 py-2.5 border-2 border-nhs-blue text-nhs-blue text-sm font-semibold rounded-full hover:bg-blue-50 transition-colors">
            Try region comparator
          </Link>
        </div>
      </div>

      {/* Impact stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
        {STATS.map((s) => (
          <div key={s.label} className="bg-white rounded-2xl border border-slate-200 p-5 text-center">
            <p className={`text-3xl font-bold mb-1 ${s.color}`}>{s.value}</p>
            <p className="text-xs text-slate-500 leading-snug">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Feature grid */}
      <div className="mb-10">
        <h2 className="text-lg font-bold text-slate-800 mb-1">Platform capabilities</h2>
        <p className="text-sm text-slate-500 mb-5">Each feature was designed to answer a real question faced by NHS analysts and policymakers.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {FEATURES.map((f) => (
            <div key={f.title} className="bg-white rounded-2xl border border-slate-200 p-5">
              <h3 className="text-sm font-bold text-slate-800 mb-2">{f.title}</h3>
              <p className="text-sm text-slate-600 leading-relaxed mb-3">{f.description}</p>
              <Link href={f.href} className="text-xs font-semibold text-nhs-blue hover:underline">
                {f.linkLabel} →
              </Link>
            </div>
          ))}
        </div>
      </div>

      {/* Innovation Statement */}
      <div className="bg-nhs-navy rounded-2xl border border-slate-800 p-6 mb-6 text-white">
        <h2 className="text-base font-bold mb-4 flex items-center gap-2">✨ What's genuinely new?</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Link href="/inequality" className="bg-slate-800 p-4 rounded-xl border border-slate-700 hover:border-nhs-blue transition-colors block">
            <h3 className="font-bold text-sm mb-1">Real-time inequality-adjusted modeling</h3>
            <p className="text-xs text-slate-300">A novel composite score tracking equity performance alongside operational metrics.</p>
          </Link>
          <Link href="/simulator" className="bg-slate-800 p-4 rounded-xl border border-slate-700 hover:border-nhs-blue transition-colors block">
            <h3 className="font-bold text-sm mb-1">AI-driven intervention simulation</h3>
            <p className="text-xs text-slate-300">Project the impact of adding surgical capacity or shifting policy dynamically.</p>
          </Link>
          <div className="bg-slate-800 p-4 rounded-xl border border-slate-700">
            <h3 className="font-bold text-sm mb-1">Unified NHS + ONS data fusion</h3>
            <p className="text-xs text-slate-300">Linking demographic deprivation automatically with hospital backlogs.</p>
          </div>
          <div className="bg-slate-800 p-4 rounded-xl border border-slate-700">
            <h3 className="font-bold text-sm mb-1">Forecasting + decision support</h3>
            <p className="text-xs text-slate-300">Moving beyond reporting tools into optimizing scarce healthcare resources.</p>
          </div>
        </div>
      </div>

      {/* Global Adaptability */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 mb-6">
        <h2 className="text-base font-bold text-slate-800 mb-4">Adaptable to Global Health Systems</h2>
        <p className="text-sm text-slate-600 mb-5 leading-relaxed">
          While currently validating against the UK NHS, the platform's modular pipeline architecture and API-first design allows rapid adaptation to other public and hybrid health systems globally.
        </p>
        <div className="flex flex-col md:flex-row gap-6">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xl">🇺🇸</span>
              <h3 className="font-bold text-slate-800 text-sm">US Medicare / Medicaid</h3>
            </div>
            <p className="text-xs text-slate-500">Pipeline configures to ingest CMS data to map rural-urban healthcare access and intervention parity.</p>
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xl">🇪🇺</span>
              <h3 className="font-bold text-slate-800 text-sm">EU Public Systems</h3>
            </div>
            <p className="text-xs text-slate-500">Easily refactors for EHR standardization formats across Germany, France, and Nordic care infrastructure.</p>
          </div>
          <div className="flex-1 border-l pl-6 border-slate-100">
            <h3 className="font-bold text-slate-800 text-sm mb-2 font-mono text-xs">Modular Architecture</h3>
            <pre className="text-[10px] text-slate-400 font-mono leading-tight">
{`[Ingest API]
  ├─ CMS mapping
  ├─ NHS RTT ETL
  └─ EU metrics
↓
[Unified Engine]
  ├─ OLS Forecast
  └─ AI Simulator
↓
[Client / PDF]`}
            </pre>
          </div>
        </div>
      </div>

      {/* Technical innovation */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 mb-6">
        <h2 className="text-base font-bold text-slate-800 mb-4">Technical innovation</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div>
            <p className="text-xs font-bold text-nhs-blue uppercase tracking-wider mb-2">AI integration</p>
            <ul className="text-sm text-slate-600 space-y-1.5">
              <li>Streaming SSE responses via Claude claude-sonnet-4-6</li>
              <li>Prompt caching for 5× cost reduction</li>
              <li>Multi-turn conversational history</li>
              <li>Autonomous SQL agent (LangChain + Haiku)</li>
              <li>Batched news triage with relevance scoring</li>
            </ul>
          </div>
          <div>
            <p className="text-xs font-bold text-amber-600 uppercase tracking-wider mb-2">Data pipeline</p>
            <ul className="text-sm text-slate-600 space-y-1.5">
              <li>Automated NHS RTT open data ingest</li>
              <li>OLS regression with 95% prediction intervals</li>
              <li>Composite inequality score (validated ρ = 0.89)</li>
              <li>PostgreSQL + SQLAlchemy on Neon</li>
              <li>CSV export for every major view</li>
            </ul>
          </div>
          <div>
            <p className="text-xs font-bold text-green-700 uppercase tracking-wider mb-2">Platform</p>
            <ul className="text-sm text-slate-600 space-y-1.5">
              <li>Next.js 14 frontend with Tailwind CSS</li>
              <li>FastAPI backend with rate limiting</li>
              <li>Leaflet choropleth interactive map</li>
              <li>Recharts for trend and specialty charts</li>
              <li>Full mobile-responsive design</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Build timeline */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 mb-6">
        <h2 className="text-base font-bold text-slate-800 mb-4">Development timeline</h2>
        <div className="relative border-l-2 border-slate-100 ml-2 space-y-5">
          {TIMELINE.map((t) => (
            <div key={t.date} className="pl-5 relative">
              <div className="absolute -left-1.5 top-1.5 w-3 h-3 rounded-full bg-nhs-blue border-2 border-white" />
              <p className="text-xs font-bold text-nhs-blue">{t.date}</p>
              <p className="text-sm text-slate-700 mt-0.5">{t.event}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Societal impact */}
      <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 mb-6">
        <h2 className="text-base font-bold text-slate-800 mb-3">Societal impact</h2>
        <div className="space-y-3 text-sm text-slate-700 leading-relaxed">
          <p>
            The NHS waiting list crisis disproportionately affects patients in deprived regions — yet the
            data that could help commissioners act is fragmented across dozens of spreadsheets. This platform
            aggregates, models, and explains that data in a single interface accessible to non-technical
            decision-makers.
          </p>
          <p>
            By combining the 18-week RTT constitutional standard, Index of Multiple Deprivation data, and
            real-time AI explanations, NHS Wait Intelligence transforms an open-data obligation into an
            actionable equity tool. Policymakers can identify which regions need the most urgent
            intervention and why — in minutes rather than days.
          </p>
          <p>
            The platform is designed to support NHS Integrated Care Boards, academic health researchers, and
            parliamentary researchers with evidence-based analysis that is reproducible, transparent, and
            openly documented in the <Link href="/methodology" className="text-nhs-blue font-medium hover:underline">methodology section</Link>.
          </p>
        </div>
      </div>

      {/* Contact / endorsement */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6">
        <h2 className="text-base font-bold text-slate-800 mb-2">Contact &amp; endorsement</h2>
        <p className="text-sm text-slate-600 mb-4">
          For research collaboration, data queries, or endorsement enquiries:
        </p>
        <div className="flex flex-wrap gap-3">
          <a
            href="mailto:phyhopeme@gmail.com"
            className="px-4 py-2 bg-nhs-navy text-white text-sm font-medium rounded-full hover:bg-nhs-blue transition-colors"
          >
            Contact via email
          </a>
          <Link href="/methodology" className="px-4 py-2 border border-slate-200 text-slate-700 text-sm font-medium rounded-full hover:bg-slate-50 transition-colors">
            Cite this work
          </Link>
          <Link href="/briefing" className="px-4 py-2 border border-slate-200 text-slate-700 text-sm font-medium rounded-full hover:bg-slate-50 transition-colors">
            Executive briefing
          </Link>
        </div>
      </div>
    </>
  )
}
