import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'


interface BriefingSection {
  heading: string
  body: string
}

interface Briefing {
  sections: BriefingSection[]
  cached: boolean
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'

const SECTION_COLORS: Record<string, string> = {
  'Situation Overview': 'border-l-blue-500 bg-blue-50',
  'Regional Analysis': 'border-l-amber-500 bg-amber-50',
  'Specialty Pressures': 'border-l-orange-500 bg-orange-50',
  'Red Flags': 'border-l-red-500 bg-red-50',
  'Policy Recommendations': 'border-l-green-500 bg-green-50',
}

const SECTION_HEADING_COLORS: Record<string, string> = {
  'Situation Overview': 'text-blue-700',
  'Regional Analysis': 'text-amber-700',
  'Specialty Pressures': 'text-orange-700',
  'Red Flags': 'text-red-700',
  'Policy Recommendations': 'text-green-700',
}

function boldify(text: string) {
  const parts = text.split(/\*\*(.*?)\*\*/g)
  return parts.map((part, i) =>
    i % 2 === 1 ? <strong key={i}>{part}</strong> : part
  )
}

export default function BriefingPage() {
  const router = useRouter()
  const [briefing, setBriefing] = useState<Briefing | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const fetchBriefing = () => {
    setLoading(true)
    setError(false)
    fetch(`${API_BASE}/api/ai-briefing`)
      .then((r) => r.json())
      .then(setBriefing)
      .catch(() => setError(true))
      .finally(() => setLoading(false))
  }

  useEffect(() => { fetchBriefing() }, [])

  const handleDownloadPdf = () => {
    // Graceful fallback to native print if jspdf not available
    window.print()
  }

  return (
    <>
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-slate-800">Executive Briefing</h1>
          <p className="text-sm text-slate-500 mt-1">
            AI-generated policy briefing from live NHS data — {today}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={fetchBriefing}
            disabled={loading}
            className="hidden md:flex items-center gap-2 px-4 py-2 text-sm font-medium border border-slate-200 rounded-full text-slate-600 hover:bg-slate-50 transition-colors disabled:opacity-40"
          >
            {loading ? 'Generating...' : 'Regenerate'}
          </button>
          <button
            onClick={handleDownloadPdf}
            disabled={loading || !briefing}
            className="hidden md:flex items-center gap-2 px-4 py-2 text-sm font-medium bg-red-600 hover:bg-red-700 text-white rounded-full transition-colors disabled:opacity-40"
          >
            Download PDF
          </button>
        </div>
      </div>

      {/* Threshold Alerts UI */}
      <div className="mb-6 bg-slate-800 rounded-2xl p-5 text-white flex justify-between items-center print:hidden">
        <div>
          <h3 className="font-bold flex items-center gap-2">
            <span className="text-amber-400">🔔</span> Configure Threshold Alerts
          </h3>
          <p className="text-xs text-slate-300 mt-1">Get notified immediately when inequality scores breach danger levels.</p>
        </div>
        <div className="flex items-center gap-3 bg-slate-900 border border-slate-700 rounded-xl px-4 py-2">
          <span className="text-sm font-semibold">Alert if score &gt;</span>
          <input type="number" defaultValue="75" className="w-16 bg-slate-800 text-white border border-slate-600 rounded px-2 py-1 text-sm outline-none" />
          <button className="bg-nhs-blue hover:bg-blue-600 px-3 py-1.5 rounded text-xs font-bold transition-colors">Save</button>
        </div>
      </div>

      {/* Metadata strip */}
      {briefing && (
        <div className="mb-5 flex items-center gap-3 text-xs text-slate-500">
          <span className="flex items-center gap-1.5">
            <span className={`w-2 h-2 rounded-full ${briefing.cached ? 'bg-amber-400' : 'bg-green-500'}`} />
            {briefing.cached ? 'Cached response (24 h)' : 'Freshly generated by Claude'}
          </span>
          <span>•</span>
          <span>{briefing.sections.length} sections</span>
          <span>•</span>
          <button
            onClick={() => router.push('/ai')}
            className="text-nhs-blue hover:underline"
          >
            Ask follow-up questions
          </button>
        </div>
      )}

      {/* Sections */}
      {loading && (
        <div className="flex flex-col gap-5">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="bg-white rounded-2xl border border-slate-200 p-6 animate-pulse">
              <div className="h-4 bg-slate-100 rounded w-40 mb-4" />
              <div className="space-y-2">
                <div className="h-3 bg-slate-100 rounded w-full" />
                <div className="h-3 bg-slate-100 rounded w-5/6" />
                <div className="h-3 bg-slate-100 rounded w-4/6" />
              </div>
            </div>
          ))}
        </div>
      )}

      {error && (
        <div className="bg-red-50 border border-red-100 rounded-2xl p-6 text-sm text-red-700">
          Could not load briefing. Make sure the backend is running and the Anthropic API key is set.
          <button onClick={fetchBriefing} className="ml-3 underline">Try again</button>
        </div>
      )}

      {briefing && !loading && (
        <div className="flex flex-col gap-5">
          {briefing.sections.map((section) => {
            const colorClass = SECTION_COLORS[section.heading] ?? 'border-l-slate-400 bg-slate-50'
            const headingColor = SECTION_HEADING_COLORS[section.heading] ?? 'text-slate-700'
            return (
              <div
                key={section.heading}
                className={`rounded-2xl border border-slate-200 border-l-4 p-6 ${colorClass}`}
              >
                <h2 className={`text-sm font-bold uppercase tracking-wider mb-3 ${headingColor}`}>
                  {section.heading}
                </h2>
                <p className="text-sm text-slate-700 leading-relaxed">
                  {boldify(section.body)}
                </p>
              </div>
            )
          })}

          <div className="flex gap-3 md:hidden">
            <button
              onClick={fetchBriefing}
              className="flex-1 py-3 border border-slate-200 rounded-full text-sm font-medium text-slate-600 hover:bg-slate-50"
            >
              Regenerate
            </button>
            <button
              onClick={handleDownloadPdf}
              className="flex-1 py-3 bg-nhs-navy text-white rounded-full text-sm font-medium"
            >
              Download
            </button>
          </div>

          <div className="bg-slate-50 rounded-2xl border border-slate-100 p-4">
            <p className="text-xs text-slate-400 leading-relaxed">
              This briefing is AI-generated using Claude Sonnet and is grounded in the latest NHS RTT data,
              ONS deprivation indices, and CQC ratings. It should be treated as an analytical aid,
              not as official NHS policy guidance. Regenerate to get an updated briefing after new data is ingested.
            </p>
          </div>
        </div>
      )}
    </>
  )
}
